# helm install --set tags.front-end=true --set subchart2.enabled=false
dependencies:
  - name: mongodb-replicaset
    version: 3.9.0
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: mongodb.enabled