version: '3.4'

networks:
  default:
    external: 
      name: ecommerce

services:
  products_service:
    container_name: products_service
    build: 
      dockerfile: Dockerfile
      context: .
    image: ecommerce/products:latest
    ports:
      - 5000:5000
    networks:
      - default
    environment:
      SERVER_PORT: "5000"
      DB_SERVER: products_mongodb
      DB_PORT: "27017"
    restart: always