trigger:
- development

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

variables:
  major-release: 0
  minor-release: 0
  azureContainerRepo: ecommerceRegistry
  azureContainerRegistry: ecommerceregistry.azurecr.io
  imageName: '$(azureContainerRegistry)/productsapi'
  imageVersion: $(major-release).$(minor-release).$(build.buildId)
  azureSubscriptionEndpoint: Resource Manager
  azureResourceGroup: ecommerce-microservices
  kubernetesCluster: Ecommerce
  chartName: productsmicroservice
  releaseName: products

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: yarn install
  displayName: 'Build'

- script: yarn test
 displayName: 'Testing'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker Build'

- task: Docker@1
  displayName: Tag image
  inputs:
    command: tag
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    imageName: $(imageName):latest
    arguments: $(imageName):$(imageVersion)

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- script: |
    docker push $(imageName)
    docker push $(imageName):$(imageVersion)
  displayName: 'Publish Latest Image on Repository'

- task: HelmDeploy@0
  displayName: Helm init
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: init
    upgradetiller: true
    waitForExecution: true
    arguments: --client-only

- task: AzureCLI@1
  displayName: Configure Helm to ACR
  inputs:
    azureSubscription: $(azureSubscriptionEndpoint)
    scriptLocation: inlineScript
    inlineScript: az acr helm repo add -n $(azureContainerRepo)

- task: HelmDeploy@0
  displayName: Helm update
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: repo
    arguments: update

- task: HelmDeploy@0
  displayName: Helm upgrade
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: upgrade
    chartType: Name
    chartName: $(azureContainerRepo)/$(chartName)
    releaseName: $(releaseName)
    install: true
    waitForExecution: false
    arguments: --set imageTag=$(imageVersion)
