# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

variables:
  major-release: 0
  minor-release: 0
  azureContainerRepo: ecommerceRegistry
  azureContainerRegistry: ecommerceregistry.azurecr.io
  imageName: '$(azureContainerRegistry)/productsapi:$(major-release).$(minor-release).$(build.buildId)'
  imageVersion: $(major-release).$(minor-release).$(build.buildId)
  azureSubscriptionEndpoint: Resource Manager
  azureResourceGroup: ecommerce-microservices
  kubernetesCluster: Ecommerce
  chartName: productsmicroservice
  

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: yarn install
  displayName: 'Build'

#- script: yarn test
#  displayName: 'Testing'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker Build'

- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)

- script: |
    docker push $(imageName)
  displayName: 'Publish Image on Repository'

- task: HelmDeploy@0
  displayName: Helm init
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: init
    upgradetiller: true
    waitForExecution: true
    arguments: --client-only

- script: |
    az acr helm repo add -n $(azureContainerRepo)
  displayName: 'Connect helm to repo'

- task: HelmDeploy@0
  displayName: Helm package
  inputs:
    command: package
    updatedependency: true
    chartPath: $(chartName)
    destination: $(Build.ArtifactStagingDirectory)
    arguments: --version $(major-release).$(minor-release).$(build.buildId)    

- task: HelmDeploy@0
  displayName: Helm upgrade
  inputs:
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: upgrade
    chartType: filepath
    chartPath: $(Build.ArtifactStagingDirectory)/$(chartName)-$(major-release).$(minor-release).$(build.buildId).tgz
    releaseName: productsapi
    install: true
    waitForExecution: false
