# ==================== Service ====================
apiVersion: v1
kind: Service
metadata:
  name: productsservice
  labels:
    app: productsapi
spec:
  type: NodePort
  selector:
    app: orderapi
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      nodePort: 31000
---
# ==================== Deployment ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsdeployment
spec:
  selector:
    matchLabels:
      app: productsapi
  template:
    metadata:
      labels:
        app: productsapi
    spec:
      containers:
        - name: productsmicroservice
          image: undermarket/products:0.0.1
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "6000"
            - name: DB_SERVER
              value: databaseservice
          ports:
            - containerPort: 6000
          readinessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 6000
            initialDelaySeconds: 30
            periodSeconds: 5
