apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productssautoscale
  namespace: {{.Values.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.deploymentName}}
  minReplicas: {{.Values.minReplicas}}
  maxReplicas: {{.Values.maxReplicas}}
  targetCPUUtilizationPercentage: {{.Values.targetCPUUtilizationPercentage}}