apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: {{.Values.namespace}}
  labels:
    app: productsapi 
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: productsapi
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{.Values.servicePort}}