apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: ecm
data:
  default.json: | 
    {"App": {"name": "Products","kind": "Api"},"Server": {"host": "localhost", "port": 5000, "enableServiceDiscovery": true, "enableAppInsights": true}, "AppInsights": {"instrumentationKey": "0aed60da-65d8-4de7-bb2d-9d22aa54f984"}, "Database": { "dbConnectionString": "mongodb://40.121.33.250/products","timeout": 20000} ,"Logs": {"logLevel": "debug","log4jsConfig": {"appenders": {"off": { "type": "console" },"mark": { "type": "console" },"error": { "type": "console" },"warn": { "type": "console" },"default": { "type": "console" },"debug": { "type": "console" },"trace": { "type": "console" },"all": { "type": "console" }},"categories": {"off": { "appenders": ["off"], "level": "off" },"mark": { "appenders": ["mark"], "level": "mark" },"error": { "appenders": ["error"], "level": "error" },"warn": { "appenders": ["warn"], "level": "warn" },"default": { "appenders": ["default"], "level": "info" },"debug": { "appenders": ["debug"], "level": "debug" },"trace": { "appenders": ["trace"], "level": "trace" },"all": { "appenders": ["all"], "level": "all" }}}}}
  eureka-client.yml: |
    instance:
      instanceId: 'productservice.ecm:products'
      app: 'PRODUCTS'
      hostName: 'productservice.ecm'
      statusPageUrl: 'http://productservice.ecm:5000'
      ipAddr: '127.0.0.1'
      port:
        '$': 5000
        '@enabled': true
      vipAddress: 'products'
      dataCenterInfo: 
        '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo'
        name: 'MyOwn'
    eureka: 
      host: 'svcdiscovery'
      port: 8761
      servicePath: '/eureka/apps'