# ==================== Service ====================
# apiVersion: v1
# kind: Service
# metadata:
#   name: productservice
#   namespace: ecm
#   labels:
#     app: productsapi
#   annotations:
#     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
# spec:
#   type: LoadBalancer
#   selector:
#     app: productsapi
#     tier: backend
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
---
# ==================== Deployment ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productsdeployment
  namespace: ecm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productsapi
      tier: backend
  template:
    metadata:
      labels:
        app: productsapi
        tier: backend
    spec:
      containers:
        - name: productsmicroservice
          image: pliniogsnascimento/productsapi:development-0.0.13
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: configs
            mountPath: /home/app/config
          resources:
            requests:
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 3600
      volumes:
        - name: configs
          configMap:
            name: products-config
            items:
            - key: development.json
              path: keys
---
# ==================== Autoscaling ====================
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: productssautoscale
#   namespace: undermarket-services
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: productsdeployment
#   minReplicas: 1
#   maxReplicas: 200
#   targetCPUUtilizationPercentage: 50
