instance:
  instanceId: 'localhost:products'
  app: 'PRODUCTS'
  hostName: 'localhost'
  statusPageUrl: 'http://localhost:5000'
  ipAddr: '127.0.0.1'
  port:
    '$': 5000
    '@enabled': true
  vipAddress: 'products'
  dataCenterInfo: 
    '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo'
    name: 'MyOwn'
eureka: 
  host: 'localhost'
  port: 8761
  servicePath: '/eureka/apps'
