apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
  namespace: {{.Values.namespace}}
data:
  default.yml: |
    App:
      name: Products
      kind: Api
      version: {{ .Values.apiVersion }}
    Server:
      host: {{.Values.serviceName}}.{{.Values.namespace}}
      port: {{default 5000 .Values.servicePort}}
      enableServiceDiscovery: true
      enableAppInsights: true
    AppInsights:
      instrumentationKey: {{.Values.appInsightsInstrumentationKey}}
    Database:
      dbConnectionString: mongodb://{{.Values.databaseServiceName}}/products
      timeout: 20000
    Logs:
      logLevel: {{.Values.logLevel}}
      log4jsConfig:
        appenders:
          'off':
            type: console
          mark:
            type: console
          error:
            type: console
          warn:
            type: console
          default:
            type: console
          debug:
            type: console
          trace:
            type: console
          all:
            type: console
        categories:
          'off':
            appenders:
            - 'off'
            level: 'off'
          mark:
            appenders:
            - mark
            level: mark
          error:
            appenders:
            - error
            level: error
          warn:
            appenders:
            - warn
            level: warn
          default:
            appenders:
            - default
            level: info
          debug:
            appenders:
            - debug
            level: debug
          trace:
            appenders:
            - trace
            level: trace
          all:
            appenders:
            - all
            level: all
  eureka-client.yml: |
    instance:
      instanceId: '{{.Values.serviceName}}.{{.Values.namespace}}:products'
      app: 'PRODUCTS'
      hostName: '{{.Values.serviceName}}.{{.Values.namespace}}'
      statusPageUrl: 'http://{{.Values.serviceName}}.{{.Values.namespace}}:{{.Values.servicePort}}'
      ipAddr: '127.0.0.1'
      port:
        '$': {{.Values.servicePort}}
        '@enabled': true
      vipAddress: 'products'
      dataCenterInfo: 
        '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo'
        name: 'MyOwn'
    eureka: 
      host: '{{.Values.host}}'
      port: {{.Values.port}}
      servicePath: '{{.Values.servicePath}}'