apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{.Values.namespace}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{.Values.app}}
      tier: {{.Values.tier}}
  template:
    metadata:
      labels:
        app: {{.Values.app}}
        tier: {{.Values.tier}}
    spec:
      containers:
        - name: productsmicroservice
          image: {{.Values.repo}}/{{.Values.image}}:{{.Values.imageTag}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.servicePort}}
          volumeMounts:
          - name: configs
            mountPath: /home/app/config
          resources:
            requests:
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /health
              port: {{.Values.servicePort}}
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{.Values.servicePort}}
            initialDelaySeconds: 30
            periodSeconds: 3600
      volumes:
        - name: configs
          configMap:
            name: products-config
            items:
            - key: {{.Values.configFileName}}
              path: {{.Values.configFileName}}
            - key: {{.Values.eurekaFileName}}
              path: {{.Values.eurekaFileName}}